export const AUTH_INIT_USER = "AUTH_INIT_USER";
export const AUTH_START_USER = "AUTH_START_USER";
export const AUTH_SUCCESS_USER = "AUTH_SUCCESS_USER";
export const AUTH_CHECK_TIMEOUT = "AUTH_CHECK_TIMEOUT";
export const AUTH_LOGOUT_USER = "AUTH_LOGOUT_USER";
export const AUTH_FAIL_USER = "AUTH_FAIL_USER";
