export const AUTH_INIT_USER = "AUTH_INIT_USER";
export const AUTH_START_USER = "AUTH_START_USER";
export const AUTH_SUCCESS_USER = "AUTH_SUCCESS_USER";
export const AUTH_CHECK_TIMEOUT = "AUTH_CHECK_TIMEOUT";
export const AUTH_INITLOGOUT_USER = "AUTH_INITLOGOUT_USER";
export const AUTH_LOGOUTSUCCESS_USER = "AUTH_LOGOUTSUCCESS_USER";
export const AUTH_FAIL_USER = "AUTH_FAIL_USER";
