export const AUTH_INIT_USER = "AUTH_INIT_USER";
//USERT START SIGNUP/SIGNIN
export const AUTH_START_USER = "AUTH_START_USER";
export const AUTH_SUCCESS_USER = "AUTH_SUCCESS_USER";
export const AUTH_CHECK_TIMEOUT = "AUTH_CHECK_TIMEOUT";
export const AUTH_INITLOGOUT_USER = "AUTH_INITLOGOUT_USER";
export const AUTH_LOGOUTSUCCESS_USER = "AUTH_LOGOUTSUCCESS_USER";
export const AUTH_FAIL_USER = "AUTH_FAIL_USER";



export const PRODUCT_START = "PRODUCT_START";
export const PRODUCT_INIT = "PRODUCT_INIT";
export const PRODUCT_SUCCESS = "PRODUCT_SUCCESS";
export const PRODUCT_FAIL = "PRODUCT_FAIL";

